# zsh plugins
[".zsh/zsh-autopair"]
    type = "git-repo"
    url = "https://github.com/hlissner/zsh-autopair"
    refreshPeriod = "168h"

[".zsh/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions"
    refreshPeriod = "168h"

[".zsh/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting"
    refreshPeriod = "168h"

[".zsh/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search"
    refreshPeriod = "168h"

[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions"
    refreshPeriod = "168h"



# tmux plugins
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
